import {
  formatReportModules,
  formatReportProjects,
  type ReportModuleId,
} from "@/lib/generated-reports-service";

const PAGE_MARGIN = 14;
const CONTENT_WIDTH = 182;

type JsPdfInstance = import("jspdf").jsPDF;

export interface ReportPdfInput {
  csvContent: string;
  startDate: string;
  endDate: string;
  projectNames: string[];
  modules: ReportModuleId[];
  actionedByName: string;
}

interface ParsedReportSection {
  title: string;
  headers: string[];
  rows: string[][];
}

function parseCsvLine(line: string): string[] {
  const result: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let index = 0; index < line.length; index += 1) {
    const char = line[index];
    if (inQuotes) {
      if (char === '"' && line[index + 1] === '"') {
        current += '"';
        index += 1;
      } else if (char === '"') {
        inQuotes = false;
      } else {
        current += char;
      }
    } else if (char === '"') {
      inQuotes = true;
    } else if (char === ",") {
      result.push(current);
      current = "";
    } else {
      current += char;
    }
  }

  result.push(current);
  return result;
}

function parseReportSections(csvContent: string): ParsedReportSection[] {
  const sections: ParsedReportSection[] = [];
  let currentTitle = "";
  let headers: string[] = [];
  let rows: string[][] = [];
  let awaitingHeader = false;

  const flush = () => {
    if (!currentTitle) return;
    sections.push({ title: currentTitle, headers, rows });
    headers = [];
    rows = [];
    awaitingHeader = false;
  };

  for (const rawLine of csvContent.split(/\r?\n/)) {
    const line = rawLine.trimEnd();
    if (!line || line.startsWith("#")) continue;

    if (line.startsWith("### ")) {
      flush();
      currentTitle = line.slice(4).trim();
      awaitingHeader = true;
      continue;
    }

    if (!currentTitle) continue;

    const cells = parseCsvLine(line);
    if (awaitingHeader) {
      headers = cells;
      awaitingHeader = false;
      continue;
    }

    rows.push(cells);
  }

  flush();
  return sections;
}

function formatDisplayDate(value: string): string {
  if (!value) return "—";
  const date = new Date(`${value.slice(0, 10)}T12:00:00`);
  if (Number.isNaN(date.getTime())) return value.slice(0, 10);
  return date.toLocaleDateString(undefined, {
    day: "numeric",
    month: "short",
    year: "numeric",
  });
}

function ensureSpace(doc: JsPdfInstance, y: number, needed: number): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - PAGE_MARGIN) {
    doc.addPage();
    return PAGE_MARGIN + 8;
  }
  return y;
}

function writeSectionHeading(doc: JsPdfInstance, title: string, y: number): number {
  let cursorY = ensureSpace(doc, y, 18);
  doc.setFillColor(255, 247, 237);
  doc.setDrawColor(251, 146, 60);
  doc.roundedRect(PAGE_MARGIN, cursorY - 6, CONTENT_WIDTH, 12, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(title, PAGE_MARGIN + 4, cursorY + 2);
  return cursorY + 14;
}

function drawCoverPage(doc: JsPdfInstance, input: ReportPdfInput): number {
  let y = 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(234, 88, 12);
  doc.text("SiteBolt", PAGE_MARGIN, y);
  y += 10;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text("Multi-Module Site Report", PAGE_MARGIN, y);
  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);

  const metaLines = [
    `Date range: ${formatDisplayDate(input.startDate)} – ${formatDisplayDate(input.endDate)}`,
    `Projects: ${formatReportProjects(input.projectNames)}`,
    `Modules: ${formatReportModules(input.modules)}`,
    `Generated by: ${input.actionedByName}`,
    `Generated at: ${new Date().toLocaleString()}`,
  ];

  for (const line of metaLines) {
    const wrapped = doc.splitTextToSize(line, CONTENT_WIDTH);
    doc.text(wrapped, PAGE_MARGIN, y);
    y += wrapped.length * 5 + 2;
  }

  return y + 8;
}

function buildPdfFileName(startDate: string, endDate: string): string {
  return `sitebolt-report-${startDate}-to-${endDate}.pdf`;
}

function attendanceBadgeColors(status: string): [number, number, number] {
  const normalized = status.toLowerCase();
  if (normalized === "worked" || normalized.startsWith("worked +")) {
    return [16, 185, 129];
  }
  if (normalized.includes("sick")) return [245, 158, 11];
  if (normalized.includes("annual leave")) return [59, 130, 246];
  if (normalized.includes("public holiday")) return [139, 92, 246];
  if (normalized.includes("rdo")) return [100, 116, 139];
  if (normalized.includes("leave")) return [249, 115, 22];
  return [148, 163, 184];
}

function isTimesheetHoursSection(title: string): boolean {
  return title.toLowerCase().includes("timesheets");
}

export async function generateReportPdfFromCsv(
  input: ReportPdfInput
): Promise<{ fileName: string; blob: Blob }> {
  const [{ jsPDF }, autoTableModule] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  const autoTable = autoTableModule.default;

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" });
  const sections = parseReportSections(input.csvContent);

  let y = drawCoverPage(doc, input);

  if (sections.length === 0) {
    y = ensureSpace(doc, y, 12);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text("No module data was available for this report.", PAGE_MARGIN, y);
  }

  for (const section of sections) {
    const timesheetSection = isTimesheetHoursSection(section.title);
    if (timesheetSection) {
      doc.addPage("a4", "landscape");
    } else {
      doc.addPage();
    }

    y = PAGE_MARGIN + 8;
    y = writeSectionHeading(doc, section.title, y);

    const head = section.headers.length > 0 ? [section.headers] : [];
    const body =
      section.rows.length > 0
        ? section.rows
        : head.length > 0
          ? [["No records in selected date range."]]
          : [["No data"]];

    const attendanceColumnIndex = section.headers.findIndex((header) =>
      header.toLowerCase().includes("attendance")
    );

    autoTable(doc, {
      startY: y,
      head: head.length > 0 ? head : undefined,
      body,
      styles: {
        font: "helvetica",
        fontSize: timesheetSection ? 7 : 8,
        cellPadding: 2,
        overflow: "linebreak",
      },
      headStyles: {
        fillColor: [251, 146, 60],
        textColor: [255, 255, 255],
        fontStyle: "bold",
      },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
      tableWidth: timesheetSection ? "auto" : CONTENT_WIDTH,
      didParseCell: (data) => {
        if (
          !timesheetSection ||
          data.section !== "body" ||
          attendanceColumnIndex < 0 ||
          data.column.index !== attendanceColumnIndex
        ) {
          return;
        }

        const status = String(data.cell.raw ?? "");
        const [r, g, b] = attendanceBadgeColors(status);
        data.cell.styles.fillColor = [r, g, b];
        data.cell.styles.textColor = [255, 255, 255];
        data.cell.styles.fontStyle = "bold";
      },
    });

    y =
      (doc as JsPdfInstance & { lastAutoTable?: { finalY: number } }).lastAutoTable
        ?.finalY ?? y + 20;
    y += 6;
  }

  const pageCount = doc.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Page ${page} of ${pageCount}`,
      doc.internal.pageSize.getWidth() - PAGE_MARGIN,
      doc.internal.pageSize.getHeight() - 8,
      { align: "right" }
    );
  }

  return {
    fileName: buildPdfFileName(input.startDate, input.endDate),
    blob: doc.output("blob"),
  };
}

export function downloadReportBlob(fileName: string, blob: Blob): void {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  anchor.rel = "noopener";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
