default_platform(:ios)

platform :ios do
  desc "Push a new build to Apple TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    increment_build_number(
      build_number: Time.now.to_i.to_s,
      xcodeproj: "App.xcodeproj"
    )

    key_path = File.expand_path("~/.appstoreconnect/private_keys/AuthKey_#{ENV['APP_STORE_CONNECT_KEY_ID']}.p8")
    FileUtils.mkdir_p(File.dirname(key_path))
    File.write(key_path, ENV["APP_STORE_CONNECT_PRIVATE_KEY"])

    build_app(
      project: "App.xcodeproj",
      scheme: "App",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "automatic",
        teamID: ENV["APPLE_TEAM_ID"],
        manageAppVersionAndBuildNumber: true,
        uploadSymbols: true
      },
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO",
      export_xcargs: "-allowProvisioningUpdates -authenticationKeyPath #{key_path} -authenticationKeyID #{ENV['APP_STORE_CONNECT_KEY_ID']} -authenticationKeyIssuerID #{ENV['APP_STORE_CONNECT_ISSUER_ID']}"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end
